// <autogenerated />
namespace History_32_List
{
	partial class MainForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			this.components = new System.ComponentModel.Container();
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
			this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
			this.mainToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
			this.historyListBox = new System.Windows.Forms.ListBox();
			this.listBoxContextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
			this.copyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.saveToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.mainStatusStrip.SuspendLayout();
			this.listBoxContextMenuStrip.SuspendLayout();
			this.SuspendLayout();
			// 
			// mainStatusStrip
			// 
			this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.mainToolStripStatusLabel});
			this.mainStatusStrip.Location = new System.Drawing.Point(0, 358);
			this.mainStatusStrip.Name = "mainStatusStrip";
			this.mainStatusStrip.Size = new System.Drawing.Size(52, 22);
			this.mainStatusStrip.SizingGrip = false;
			this.mainStatusStrip.TabIndex = 0;
			this.mainStatusStrip.Text = "statusStrip1";
			// 
			// mainToolStripStatusLabel
			// 
			this.mainToolStripStatusLabel.Font = new System.Drawing.Font("Tahoma", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.mainToolStripStatusLabel.Margin = new System.Windows.Forms.Padding(0);
			this.mainToolStripStatusLabel.Name = "mainToolStripStatusLabel";
			this.mainToolStripStatusLabel.Size = new System.Drawing.Size(16, 22);
			this.mainToolStripStatusLabel.Text = "0";
			this.mainToolStripStatusLabel.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			// 
			// historyListBox
			// 
			this.historyListBox.Dock = System.Windows.Forms.DockStyle.Fill;
			this.historyListBox.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
			this.historyListBox.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.historyListBox.FormattingEnabled = true;
			this.historyListBox.IntegralHeight = false;
			this.historyListBox.Location = new System.Drawing.Point(0, 0);
			this.historyListBox.Name = "historyListBox";
			this.historyListBox.Size = new System.Drawing.Size(52, 358);
			this.historyListBox.TabIndex = 1;
			this.historyListBox.DrawItem += new System.Windows.Forms.DrawItemEventHandler(this.OnHistoryListBoxDrawItem);
			// 
			// listBoxContextMenuStrip
			// 
			this.listBoxContextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.copyToolStripMenuItem,
									this.saveToolStripMenuItem});
			this.listBoxContextMenuStrip.Name = "listBoxContextMenuStrip";
			this.listBoxContextMenuStrip.Size = new System.Drawing.Size(153, 70);
			// 
			// copyToolStripMenuItem
			// 
			this.copyToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("copyToolStripMenuItem.Image")));
			this.copyToolStripMenuItem.Name = "copyToolStripMenuItem";
			this.copyToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
			this.copyToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
			this.copyToolStripMenuItem.Text = "&Copy";
			this.copyToolStripMenuItem.Click += new System.EventHandler(this.OnCopyToolStripMenuItemClick);
			// 
			// saveToolStripMenuItem
			// 
			this.saveToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("saveToolStripMenuItem.Image")));
			this.saveToolStripMenuItem.Name = "saveToolStripMenuItem";
			this.saveToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.S)));
			this.saveToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
			this.saveToolStripMenuItem.Text = "&Save";
			this.saveToolStripMenuItem.Click += new System.EventHandler(this.OnSaveToolStripMenuItemClick);
			// 
			// MainForm
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(52, 380);
			this.ControlBox = false;
			this.Controls.Add(this.historyListBox);
			this.Controls.Add(this.mainStatusStrip);
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.SizableToolWindow;
			this.MaximizeBox = false;
			this.MinimizeBox = false;
			this.Name = "MainForm";
			this.Text = "History";
			this.mainStatusStrip.ResumeLayout(false);
			this.mainStatusStrip.PerformLayout();
			this.listBoxContextMenuStrip.ResumeLayout(false);
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		private System.Windows.Forms.ToolStripMenuItem saveToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem copyToolStripMenuItem;
		private System.Windows.Forms.ContextMenuStrip listBoxContextMenuStrip;
		private System.Windows.Forms.ListBox historyListBox;
		private System.Windows.Forms.ToolStripStatusLabel mainToolStripStatusLabel;
		private System.Windows.Forms.StatusStrip mainStatusStrip;
	}
}
